import { readFile, readFileSync } from 'fs';
import * as Q from 'q';
import { validateArgument } from './utils/validate';
const supportedReturnAs = ['utf8', 'buffer', 'json', 'jsonWithDates'];
export function validateInput(methodName: string, path: string, returnAs: string) {
  const methodSignature = methodName + '(path, returnAs)';
  validateArgument(methodSignature, 'path', path, ['string']);
  validateArgument(methodSignature, 'returnAs', returnAs, ['string', 'undefined']);
  if (returnAs && supportedReturnAs.indexOf(returnAs) === -1) {
    throw new Error('Argument "returnAs" passed to ' + methodSignature
      + ' must have one of values: ' + supportedReturnAs.join(', '));
  }
};

// Matches strings generated by Date.toJSON()
// which is called to serialize date to JSON.
const jsonDateParser = function (key: string, value: any) {
  var reISO = /^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2}(?:\.\d*))(?:Z|(\+|-)([\d|:]*))?$/;
  if (typeof value === 'string') {
    if (reISO.exec(value)) {
      return new Date(value);
    }
  }
  return value;
};

function makeNicerJsonParsingError(path: string, err: any) {
  const nicerError: any = new Error('JSON parsing failed while reading '
    + path + ' [' + err + ']');
  nicerError.originalError = err;
  return nicerError;
};

// ---------------------------------------------------------
// SYNC
// ---------------------------------------------------------
export function sync(path: string, returnAs?: string) {
  const retAs = returnAs || 'utf8';
  let data;
  let encoding: string = 'utf8';
  if (retAs === 'buffer') {
    encoding = null;
  }

  try {
    data = readFileSync(path, { encoding: encoding });
  } catch (err) {
    if (err.code === 'ENOENT') {
      // If file doesn't exist return undefined instead of throwing.
      return undefined;
    }
    // Otherwise rethrow the error
    throw err;
  }

  try {
    if (retAs === 'json') {
      data = JSON.parse(data);
    } else if (retAs === 'jsonWithDates') {
      data = JSON.parse(data, jsonDateParser);
    }
  } catch (err) {
    throw makeNicerJsonParsingError(path, err);
  }

  return data;
};

// ---------------------------------------------------------
// ASYNC
// ---------------------------------------------------------
const promisedReadFile = Q.denodeify(readFile);
export function async(path: string, returnAs?: string) {
  return new Promise((resolve, reject) => {
    const retAs = returnAs || 'utf8';
    let encoding: string = 'utf8';
    if (retAs === 'buffer') {
      encoding = null;
    }

    promisedReadFile(path, { encoding: encoding })
      .then(data => {
        // Make final parsing of the data before returning.
        try {
          if (retAs === 'json') {
            resolve(JSON.parse(data));
          } else if (retAs === 'jsonWithDates') {
            resolve(JSON.parse(data, jsonDateParser));
          } else {
            resolve(data);
          }
        } catch (err) {
          reject(makeNicerJsonParsingError(path, err));
        }
      })
      .catch(function (err) {
        if (err.code === 'ENOENT') {
          // If file doesn't exist return undefined instead of throwing.
          resolve(undefined);
        } else {
          // Otherwise throw
          reject(err);
        }
      });
  });
};
